import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/lifestyle',
          '/location',
          '/storyline',
          '/member-benefits',
          '/news',
          '/furniture-demo',
          '/iot',
          '/assets/',
          '/Logo_',
          '/background/',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/_next/',
          '/private/',
          '/test/',
          '/temp/',
          '/draft/',
          '/preview/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/lifestyle',
          '/location',
          '/storyline',
          '/member-benefits',
          '/news',
          '/furniture-demo',
          '/iot',
          '/assets/',
          '/Logo_',
          '/background/',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/_next/',
          '/private/',
          '/test/',
          '/temp/',
          '/draft/',
          '/preview/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot-Image',
        allow: [
          '/assets/',
          '/public/',
          '/Logo_',
          '/background/',
          '/assets/home/',
          '/assets/lifestyle/',
          '/assets/location/',
          '/assets/storyline/',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/_next/',
          '/private/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/lifestyle',
          '/location',
          '/storyline',
          '/member-benefits',
          '/news',
          '/furniture-demo',
          '/iot',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/_next/',
          '/private/',
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: 'https://pleviacity.vn/sitemap.xml',
    host: 'https://pleviacity.vn',
  };
} 